### ISSUE TITLE
whitelist a camel case class not working

### ISSUE THREAD

**Issue by pldg** [webpack-contrib/purifycss-webpack#134]
Not working:

`whitelist: ['*doNotRemove*']`

```css
.doNotRemove-this-class {
  color: red;
}
```

This works fine:

`whitelist: ['*do_not_remove*']`

```css
.do_not_remove-this-class {
  color: red;
}
```
